### ISSUE TITLE
Promise based API

### ISSUE THREAD

**Issue by ameyms** [d3/d3-xhr#1]
Would you have any plans to implement promise based APIs?

**Comment by mbostock** [comment]
Not at the moment.

**Comment by curran** [comment]
It's easily wrappable:

```javascript
function xhrAsPromise(url){
  return new Promise(function (resolve, reject){
    xhr(url, function(error, request) {
      if(error) {
        reject(error);
      } else {
        resolve(request);
      }
    });
  });
}
```

**Comment by mbostock** [comment]
From @aendrew in mbostock/d3#2684:

Howdy!

As we move ever-closer to the shiny-happy ES2015 future, I was wondering whether there's any interest in having the data functions return promises somehow. My initial thought is to leave them function as per normal when a callback is specified, but otherwise return a ES6 promise. This would allow for some really cool programming patterns using the new ES7 async/await syntax, and allow intelligent loading of multiple datasets without resorting to something like `d3.queue`. Consider how straight-forward and just generally _nice_ this looks:

```js
let data1 = await d3.json('./data/myData.json');
d3.selectAll('.things').data(data1).enter().append('circle'); // or whatever — jump straight to the fun part!
```

Compare that to the normal syntax:
```js
d3.json('./data/myData.json', function(err, data) {
  d3.selectAll('.things').data(data1).enter().append('circle'); // Not bad but still verbose.
});
```

Or worse, the current way of implementing a promise in ES2015:
```js
let p1 = new Promise((res, rej) => {
  d3.json('./data/myData.json', function(err, data) {
    err ? rej(err) : res(data);
  });
});

p1.then((data1) => {
  d3.selectAll('.things').data(data1).enter().append('circle'); // Good lord, what a mess.
});
```

I know that D3 has [generally opted to stay in ES5 land](https://github.com/mbostock/d3/issues/2220) for the moment (save for module loading), but is this something that's being considered? Would happily write a PR if so!

**Comment by mbostock** [comment]
It’s already the case that the request function (such as [json](https://github.com/d3/d3-request#json), or d3.json in 3.x) returns a request object, and that you can call it without a callback. However, if you don’t specify a callback, then the request isn’t opened until you call [*request*.send](https://github.com/d3/d3-request#request_send) or an equivalent convenience function such as [*request*.get](https://github.com/d3/d3-request#request_get). That’s necessary for configuring the request before it’s sent.

It’s also possible to call *request*.send (and likewise *request*.get) without a callback, in which case you can listen for “load” and “error” events. I suppose it’d be possible to replace that interface with a promises implementation. But it’s not ideal since we still want to support beforesend and progress events, so promises would just present yet another call pattern.

The integration with let & await is a strong argument, but it feels too early at this point to be adopting promises for ES7 language features. But it might make sense a year from now when there’s broader adoption.

**Comment by curran** [comment]
If promises were to be adopted in D3 modules, that would *force* developers using D3 and targeting IE to adopt a polyfill (such as [es6-promise](https://github.com/jakearchibald/es6-promise)), which is not ideal. Promises are still not supported in IE and Opera Mini (according to [caniuse.com](http://caniuse.com/#feat=promises)).

Maybe one alternative would be to create an additional tiny module specifically for folks like @aendrew who are using ES2015 that provides a thin wrapper around d3-request that exposes the API using promises. I suppose with the advent of Rollup and tree shaking it might even make sense to have a "d3-es7" module that wraps all of D3 with more idiomatic ES7-style APIs that take full advantage of fancy things like let & await.

**Comment by aendrew** [comment]
Hi all!
@mbostock, thanks for getting back to me, much appreciated. :smile: 

I agree that it's probably still a bit too early, and particularly for those who care about IE support (I didn't even realise IE11 didn't support promises. That's ludicrous!). Polyfilling isn't really an issue for those of us using ES6/7 language features and transpiling through Babel (or possibly TypeScript; we do that already. For others, however, it *is* quite an annoying addition. 

I really like @curran's idea of creating an ES7 wrapper for `d3-request`, or even creating a `d3-futuretech` wrapper that exposes those APIs in a more idiomatic way — @curran, any idea what else could be added to that? I'm writing a book on D3 in ES2015 right now and so far the request functions are the only place thus far where D3 hasn't felt brilliant in that environment (FWIW, *it is _so_ nice* writing D3 in ES2015 — it seriously feels like you do half as much typing).

**Comment by mbostock** [comment]
A d3-es7 (or d3-es2016?) module would go against the modularity of D3 4.0, since such a module would be inherently monolithic. The whole idea of D3 4.0 is that you can pick and choose the modules you need to form your own custom build. So, a d3-request-promise module would be my preferred solution: it would wrap the d3-request API with promises. That way you can use promises, or [queue](https://github.com/mbostock/queue), as you like.

**Comment by aendrew** [comment]
@mbostock Fair enough; that's a good good point re: architecture. 

Given that — would it be better to write such a thing as a separate repo or to just PR d3-request?

**Comment by aendrew** [comment]
FWIW, I've been taking a look at how [kristw/d3.promise](https://github.com/kristw/d3.promise/blob/master/src/d3.promise.js) does things and it ain't bad for the convenience functions, at least. I've been working on a TypeScript wrapper in the meantime, WIP version at aendrew/d3-request-promises.
